apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: user-service
              tier: backend
        spec:
            containers:
            - name: user-service
              image: sleepingtalent/user-service:@docker.release.version@
              readinessProbe:
                httpGet:
                  path: /user-service/health
                  port: 2222
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              livenessProbe:
                httpGet:
                  path: /user-service/health
                  port: 2222
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              env:
              - name: CONFIG_URL
                value: http://10.52.180.42:1111/config-api/
              ports:
              - containerPort: 2222

---

kind: Service
metadata:
    name: user-service-gateway
    labels:
        app: user-service
        tier: backend
spec:
    type: LoadBalancer
    ports:
    - port: 2222
    selector:
        app: user-service
        tier: backend
